name: mint
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - python=3.7.12
  - pip=24.0
  - cudatoolkit=11.3.1
  - biopython=1.79
  - biotite=0.31.0
  - einops=0.7.0
  - fairscale=0.4.3
  - hhsuite=3.3.0
  - hmmer=3.3.2
  - hydra-core=1.3.2
  - ipykernel=6.15.2
  - ipython=7.31.1
  - jupyter_client=7.4.9
  - jupyter_core=4.11.2
  - kalign2=2.04
  - omegaconf=2.3.0
  - openmm=7.5.1
  - pandas=1.3.5
  - pdbfixer=1.7
  - pytest=7.4.4
  - pip:
      - torch==1.12.1
      - torchvision==0.13.1
      - torchaudio==0.12.1
      - absl-py==2.1.0
      - datasets==2.13.2
      - deepspeed==0.5.9
      - filelock==3.12.2
      - fire==0.5.0
      - gdown==4.7.3
      - huggingface-hub==0.16.4
      - jupyterlab-widgets==3.0.10
      - lightning==1.9.5
      - matplotlib==3.5.3
      - numpy==1.21.2
      - openpyxl==3.1.3
      - protobuf==3.20.3
      - rdkit-pypi==2022.9.5
      - regex==2024.4.16
      - requests==2.26.0
      - scikit-learn==1.0.2
      - scipy==1.7.1
      - sentencepiece==0.2.0
      - tqdm==4.67.1