name: mint
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - jupyterlab
  - python=3.10
  - pip
  - cudatoolkit
  - biopython
  - einops
  - fairscale
  - hhsuite
  - hmmer
  - hydra-core
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - kalign2
  - omegaconf
  - openmm
  - pandas
  - pdbfixer
  - pytest
  - pytorch
  - pytorch-mutex
  - pip:
      - absl-py
      - datasets
      - deepspeed
      - filelock
      - huggingface-hub
      - jupyterlab-widgets
      - lightning
      - matplotlib
      - numpy
      - openpyxl
      - protobuf
      - rdkit-pypi
      - regex
      - requests
      - scikit-learn
      - scipy
      - sentencepiece
      - easydict
      - lmdb
      - gdown
      - wandb
      - transformers
      - dgeb
      - ipywidgets
      - line_profiler
      - -e /home/ubuntu/esm